# Generated by Django 3.2.8 on 2021-11-20 19:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20211120_1713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserOrdersProfile',
        ),
    ]
