# Generated by Django 3.2.8 on 2021-11-21 13:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0007_rename_user_orders_profile_order_user_profile'),
        ('profiles', '0003_rename_userprofile_userordersprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserOrdersProfile',
            new_name='UserProfile',
        ),
    ]
