# Generated by Django 3.2.8 on 2021-10-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kicks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KicksType',
            new_name='Type',
        ),
        migrations.AlterModelOptions(
            name='kicks',
            options={'verbose_name_plural': 'Kicks'},
        ),
    ]
