# Generated by Django 3.2.8 on 2021-10-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kicks', '0002_auto_20211019_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='kicks',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
