# Generated by Django 3.2.8 on 2021-10-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kicks', '0004_auto_20211021_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kicks',
            name='default_image',
        ),
        migrations.AddField(
            model_name='kicks',
            name='image1_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='kicks',
            name='image2_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='kicks',
            name='image3_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
