# Generated by Django 3.2.8 on 2021-10-30 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_sex_options'),
        ('kicks', '0005_auto_20211021_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='kicks',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.sex'),
        ),
    ]
