# Generated by Django 3.2.8 on 2021-10-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sex',
            options={'verbose_name_plural': 'sex'},
        ),
    ]
