# Generated by Django 3.2.8 on 2021-10-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_sex_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sex',
            old_name='sex',
            new_name='name',
        ),
    ]
