# Generated by Django 3.2.8 on 2021-11-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_rename_sex_sex_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sex',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sex',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
