# Generated by Django 3.2.8 on 2021-11-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20211101_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='name',
            field=models.CharField(default='size', max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.JSONField(default=list),
        ),
    ]
