# Generated by Django 3.2.8 on 2021-11-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_profile',
            new_name='user_orders_profile',
        ),
    ]
