# Generated by Django 3.2.8 on 2021-11-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211106_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(default='discount', max_length=254),
        ),
        migrations.AddField(
            model_name='home',
            name='name',
            field=models.CharField(default='home', max_length=254),
        ),
    ]
