# Generated by Django 3.2.8 on 2021-11-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211106_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='home',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
