# Generated by Django 3.2.8 on 2021-11-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211123_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='logo',
            new_name='loader_logo',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='logo_url',
            new_name='loader_logo_url',
        ),
        migrations.AddField(
            model_name='home',
            name='main_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='home',
            name='main_logo_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
