# Generated by Django 3.2.8 on 2021-10-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessories',
            options={'verbose_name_plural': 'Accessories'},
        ),
        migrations.RenameField(
            model_name='accessories',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='accessories',
            old_name='image_url',
            new_name='image1_url',
        ),
        migrations.AddField(
            model_name='accessories',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='accessories',
            name='image2_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='accessories',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='accessories',
            name='image3_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
