# Generated by Django 3.2.8 on 2021-11-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0003_rename_accessory_type_accessories_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='sku',
            field=models.CharField(max_length=254),
        ),
    ]
